[build]
  command = "npm run build"  # Adjust this command based on your build process
  functions = "out/functions"  # The path to your Netlify Functions

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
